### ISSUE TITLE
Order of Latitude and Longitude seems inconsistent in GeoJSON export

### ISSUE THREAD

**Issue by Koumi460** [TechnoServe/TerraTrac-Mobile#7]
Hi, 

From my very limited testing of the app, it seems that when exporting data in GeoJSON, in the geometry section of the file the coordinate pairs are [latitude, longitude] when the geometry is a point, but [longitude, latitude] when the type is polygon.

Could you please check on that and let me know if this is intentional?

Thanks, 

Jan

**Comment by lucienshema** [comment]
Hi, 
Thanks for the feedback, which app version did you check ? you can check the recent version the issue is fixed. 
Thanks, 
Lucien

**Comment by Koumi460** [comment]
Hi, 
Sorry for the late response. I have now tried the latest version 2.51 that my phone updated just over a week ago and I think the issue is still there.
The polygon export is fine. In the properties section of the GeoJSON and on the CSV export are all correct. But in the coordinates section of the exported geojson file the point is reported as [latitude, longitude].
Thanks,
Jan

**Comment by Koumi460** [comment]
Sorry, didn't mean to close.
